### ISSUE TITLE
Missing initial deployment description

### ISSUE THREAD

**Issue by LutzLange** [jamesread/dotnetcore-city-info#1]
The initial deployment description for the dotcore-city-info application is missing in your Readme.

**Comment by LutzLange** [comment]
Your screen shot for the initial deploy has a .NET version 1.0 selected. Your text tells people to explicity use .NET 2.0.

**Comment by jamesread** [comment]
Hey Lutz. Thanks so much for taking the time to raise this issue. I believe commit fddf0c6de094b63e3b96e1be986c36554f7b969d should fix this. Do you agree?
