### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by dynamicdusa** [jamesread/dotnetcore-city-info#5]
Hello - the build is not working when I try to create a new image from Openshift 3.7

Cloning "https://github.com/jamesread/dotnetcore-city-info " ...
	Commit:	0fde0504c2c5cbf2c5ed997af0284c6490e5bcd3 (#1 Made description even clearer (hopefully!))
	Author:	jamesread <contact@jwread.com>
	Date:	Tue Feb 27 13:18:47 2018 +0000
---> Copying application source ...
---> Installing dependencies ...
warn : The folder '/opt/app-root/src' does not contain a project to restore.
---> Building application ...
Couldn't find 'project.json' in '.'
error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnetcore-10-rhel7@sha256:3380416a1e018bb6a82dca1b4cc5bfb938db72123f8a4988e0ff7d1569e91f55

**Comment by jamesread** [comment]
Hi there @dynamicdusa . The reason that you are probably seeing this error is that you may have selected a "version 1" builder in the configuration. This project needs a "version 2" builder. 

Please see the [README](../blob/master/README.rst) for detailed instructions on building this project. Feel free to come back and ask for help if you need it ;)

**Comment by dynamicdusa** [comment]
Perfect thanks - working fine now!
